/**
 * Action types.
 * @module constants/ActionTypes
 */

export const APP_CONFIG = 'APP_CONFIG';
export const REGISTER = 'REGISTER';
export const SIMPLE_REGISTRATION = 'SIMPLE_REGISTRATION';
export const QUICK_REGISTRATION = 'QUICK_REGISTRATION';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const USER_PLACE_SESSION = 'USER_PLACE_SESSION';
export const EMAIL_SAVE = 'EMAIL_SAVE';
export const EMAIL_EXISTS = 'EMAIL_EXISTS';
export const PASSWORD_SAVE = 'PASSWORD_SAVE';
export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const VERIFY_EMAIL_START = 'VERIFY_EMAIL_START';
export const VERIFY_EMAIL_COMPLETE = 'VERIFY_EMAIL_COMPLETE';
export const GET_SERVICE_PROVIDER = 'GET_SERVICE_PROVIDER';
export const USER_ATTRIBUTES_LOAD = 'USER_ATTRIBUTES_LOAD';
export const USER_ATTRIBUTE_RESET = 'USER_ATTRIBUTE_RESET';
export const USER_ATTRIBUTE_CREATE = 'USER_ATTRIBUTE_CREATE';
export const USER_ATTRIBUTE_SAVE = 'USER_ATTRIBUTE_SAVE';
export const DISPLAY_NAME = 'DISPLAY_NAME';
export const APP_MENU_HIDE = 'APP_MENU_HIDE';
export const APP_MENU_SHOW = 'APP_MENU_SHOW';
// IRMA
export const REQUEST_IRMA_SESSIONTOKEN = 'REQUEST_IRMA_SESSIONTOKEN';
export const POLL_IRMA_LOGIN = 'POLL_IRMA_LOGIN';
export const REQUEST_IRMA_ISSUETOKEN = 'REQUEST_IRMA_ISSUETOKEN';
export const POLL_IRMA_ISSUE = 'POLL_IRMA_LOGIN';
